billions/api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('', views.apiOverview, name='api'),
    path('reference-list/', views.referenceList, name='reference-list'),
    path('reference-detail/<str:pk>/', views.referenceDetail, name='reference-detail'),
]

billions/billions/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('api/', include('api.urls', namespace='api')),
    path('', include('references.urls', namespace='references'))
]

billions/references/urls.py
from django.urls import path
from . import views

app_name='references'

urlpatterns = [
    path('reference/<slug:slug>/', views.detail_view, name='detail_view'),
    path('references/', views.list_view, name='list_view'),
    path('references/<slug:tag_slug>/', views.list_view, name='list_view_by_tag'),
    path('episode/<int:episode_number>/', views.list_view, name='list_view_by_episode'),
    path('seasons/', views.season_list_view, name='seasons_list'),
    path('seasons/<int:season_number>/', views.season_detail_view, name='season_view'),
    path('characters/', views.character_list_view, name='characters'),
    path('character/', views.character_detail_view, name='character')
]

billions/references/models.py
from django.db import models
from django.utils.text import slugify
from taggit.managers import TaggableManager

class Season(models.Model):
    number = models.IntegerField()
    year = models.IntegerField()
    poster = models.ImageField(blank=True)

    def __str__(self):
        return str(self.number)

    class Meta:
        ordering = ['-number']


class Episode(models.Model):
    number = models.IntegerField()
    season = models.ForeignKey(Season,
                               on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    aired = models.DateField()

    def __str__(self):
        return str(self.number)

    class Meta:
        ordering = ['number']


class ReferenceCategory(models.Model):
    category = models.CharField(max_length=25)

    def __str(self):
        return self.type


class Character(models.Model):
    name = models.CharField(max_length=50)
    aka = models.CharField(max_length=25)
    slug = models.SlugField(max_length=25,
                            blank=True)
    img_small = models.ImageField(blank=True)
    img_large = models.ImageField(blank=True)
    actor = models.CharField(max_length=50)
    imdb_link = models.URLField(max_length=200,
                                blank=True)

    def __str__(self):
        return self.aka

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.aka)
        super().save(*args, **kwargs)


class Reference(models.Model):
    season = models.ForeignKey(Season,
                               on_delete=models.CASCADE)
    episode = models.ForeignKey(Episode,
                                on_delete=models.CASCADE)
    characters = models.ManyToManyField(Character)
    category = models.ForeignKey(ReferenceCategory,
                                 null=True,
                                 blank=True,
                                 on_delete=models.SET_NULL)
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=100,
                           blank=True)
    time = models.TimeField()
    image = models.ImageField(blank=True)
    dialog = models.TextField(max_length=1000)
    explanation = models.TextField(max_length=2000)
    tags = TaggableManager(blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['season', 'episode', 'time']

billions/references/views.py
from django.shortcuts import render, get_object_or_404
from .models import Season, Episode, Reference, ReferenceCategory, Character
from taggit.models import Tag

def detail_view(request, slug):
    reference = get_object_or_404(Reference, slug=slug)
    characters = reference.characters.all()
    if not reference.slug:
        refrence.slug = slugify(reference.title)

    context = {'reference': reference,
               'characters': characters}
    return render(request,
                  'references/reference/detail.html',
                  context)

def list_view(request, tag_slug=None, episode_number=None):
    references = Reference.objects.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        references = references.filter(tags__in=[tag])
    if episode_number:
        references = references.filter(episode=episode_number)
    for reference in references:
        reference.faces = reference.characters.all()
        print(reference.faces)
        print(reference.characters.all())
    return render(request,
                  'references/reference/list.html',
                  {'references': references})


def season_list_view(request):
    seasons = Season.objects.all()
    return render(request,
                  'references/seasons/list.html',
                  {'seasons': seasons})

def season_detail_view(request, season_number=None):
    season = Season.objects.get(number=season_number)
    episodes = Episode.objects.filter(season=season_number)
    return render(request,
                  'references/seasons/detail.html',
                  {'season': season,
                   'episodes': episodes})

def character_detail_view(request, aka):
    character = Character.objects.get(aka=aka)
    return render(request,
                  'references/characters/detail.html',
                  {'charachter': character})

def character_list_view(request):
    characters = Character.objects.all()
    return render(request,
                  'references/characters/list.html',
                  {'characters': characters})

billions/references/templates/references/seasons/detail.html
{% extends 'references/base.html' %}
{% load static %}

{% block title %}Season {{ season.number }}{% endblock %}

{% block content %}
    <h1> Season {{ season.number }}</h1>
    <div class="card-group">
        {% for episode in episodes %}
            <div class="card">
                <a href="#"><img src="..." class="card-img-top" alt="..."></a>
                <div class="card-body">
                    <h5 class="card-title">{{ episode.title }}</h5>
                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                    <a href="#"><p class="card-text"><small class="text-muted"><a href="{% url 'references:list_view_by_episode' episode.number %}">References</small></p></a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

billions/references/templates/references/seasons/episode_list.html
{% extends 'references/base.html' %}
{% load static %}

{% block title %}Episodes
    {% if season_number %}
        Season {{ season_number }}
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Episodes
    {% if season_number %}
        Season {{ season_number }}
    {% endif %}
    </h1>
{% endblock %}

billions/references/templates/references/seasons/list.html
{% extends 'references/base.html' %}
{% load static %}

{% block title %}Seasons{% endblock %}

{% block content %}
    <h1>Seasons</h1>
    {% for season in seasons %}
        {{ season.number }}
        <div class="card mb-3">
            <img src="" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Season {{ season.number }}</h5>
                <p class="card-text">{{ season.year }}</p>
                <p class="card-text"><small class="text-muted"><a href="{% url 'references:season_view' season.number %}">Episodes</a></small></p>
            </div>
        </div>




    {% endfor %}

{% endblock %}