billions/api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('', views.apiOverview, name='api'),
    path('reference-list/', views.referenceList, name='reference-list'),
    path('reference-detail/<str:pk>/', views.referenceDetail, name='reference-detail'),
]

billions/billions/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('api/', include('api.urls', namespace='api')),
    path('', include('references.urls', namespace='references'))
]

billions/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail')
]

billions/references/urls.py
from django.urls import path
from . import views

app_name='references'

urlpatterns = [
    path('reference/<slug:slug>/', views.detail_view, name='detail_view'),
    path('references/', views.list_view, name='list_view'),
    path('references/<slug:tag_slug>/', views.list_view, name='list_view_by_tag'),
    path('episode/<int:episode_number>/', views.list_view, name='list_view_by_episode'),
    path('seasons/', views.season_list_view, name='seasons_list'),
    path('seasons/<int:season_number>/', views.season_detail_view, name='season_view'),
    path('characters/', views.character_list_view, name='characters'),
    path('character/', views.character_detail_view, name='character')
]

billions/references/models.py
from django.db import models
from django.utils.text import slugify
from taggit.managers import TaggableManager

class Season(models.Model):
    number = models.IntegerField()
    year = models.IntegerField()
    poster = models.ImageField(blank=True)

    def __str__(self):
        return str(self.number)

    class Meta:
        ordering = ['-number']


class Episode(models.Model):
    number = models.IntegerField()
    season = models.ForeignKey(Season,
                               on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    aired = models.DateField()

    def __str__(self):
        return str(self.number)

    class Meta:
        ordering = ['number']


class ReferenceCategory(models.Model):
    category = models.CharField(max_length=25)

    def __str(self):
        return self.type


class Character(models.Model):
    name = models.CharField(max_length=50)
    aka = models.CharField(max_length=25)
    slug = models.SlugField(max_length=25,
                            blank=True)
    img_small = models.ImageField(blank=True)
    img_large = models.ImageField(blank=True)
    actor = models.CharField(max_length=50)
    imdb_link = models.URLField(max_length=200,
                                blank=True)

    def __str__(self):
        return self.aka

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.aka)
        super().save(*args, **kwargs)


class Reference(models.Model):
    season = models.ForeignKey(Season,
                               on_delete=models.CASCADE)
    episode = models.ForeignKey(Episode,
                                on_delete=models.CASCADE)
    characters = models.ManyToManyField(Character)
    category = models.ForeignKey(ReferenceCategory,
                                 null=True,
                                 blank=True,
                                 on_delete=models.SET_NULL)
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=100,
                           blank=True)
    time = models.TimeField()
    image = models.ImageField(blank=True)
    dialog = models.TextField(max_length=1000)
    explanation = models.TextField(max_length=2000)
    tags = TaggableManager(blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['season', 'episode', 'time']

billions/references/views.py
from django.shortcuts import render, get_object_or_404
from .models import Season, Episode, Reference, ReferenceCategory, Character
from taggit.models import Tag

def detail_view(request, slug):
    reference = get_object_or_404(Reference, slug=slug)
    characters = reference.characters.all()
    if not reference.slug:
        refrence.slug = slugify(reference.title)

    context = {'reference': reference,
               'characters': characters}
    return render(request,
                  'references/reference/detail.html',
                  context)

def list_view(request, tag_slug=None, episode_number=None):
    references = Reference.objects.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        references = references.filter(tags__in=[tag])
    if episode_number:
        references = references.filter(episode=episode_number)
    for reference in references:
        reference.faces = reference.characters.all()
        print(reference.faces)
        print(reference.characters.all())
    return render(request,
                  'references/reference/list.html',
                  {'references': references})


def season_list_view(request):
    seasons = Season.objects.all()
    return render(request,
                  'references/seasons/list.html',
                  {'seasons': seasons})

def season_detail_view(request, season_number=None):
    season = Season.objects.get(number=season_number)
    episodes = Episode.objects.filter(season=season_number)
    return render(request,
                  'references/seasons/detail.html',
                  {'season': season,
                   'episodes': episodes})

def character_detail_view(request, aka):
    character = Character.objects.get(aka=aka)
    return render(request,
                  'references/characters/detail.html',
                  {'charachter': character})

def character_list_view(request):
    characters = Character.objects.all()
    return render(request,
                  'references/characters/list.html',
                  {'characters': characters})

billions/references/templates/references/base.html
{% load static %}
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <title>Billions</title>
        <link href="{% static 'css/bootstrap.min.css' %}" rel='stylesheet' type="text/css">
        <link href="{% static 'css/blog.css' %}" rel="stylesheet", type="text/css">
    </head>

    <body>
        <header class="blog-header py-3">
            <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-4 pt-1">
                <a class="text-muted" href="#">Subscribe</a>
            </div>
            <div class="col-4 text-center">
                <a class="blog-header-logo text-dark" href="#">BILLIONS</a>
            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">
                <a class="text-muted" href="#" aria-label="Search">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24" focusable="false"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
                </a>
                <a class="btn btn-sm btn-outline-secondary" href="#">Sign up</a>
            </div>
            </div>
        </header>

        <div class="nav-scroller py-1 mb-2">
            <nav class="nav d-flex justify-content-between">
                <a class="p-2 text-muted" href="{% url 'blog:post_list' %}">Blog</a>
                <a class="p-2 text-muted" href="{% url 'references:list_view' %}">References</a>
                <a class="p-2 text-muted" href="{% url 'references:seasons_list' %}">Seasons</a>
                <a class="p-2 text-muted" href="{% url 'references:characters' %}">Characters</a>
                <a class="p-2 text-muted" href="#">Songlist</a>
            </nav>
        </div>

        <div id="content">
            {% block content %}
            {% endblock %}
        </div>

    </body>

</html>